### ISSUE TITLE
Please remove the automatic header regeneration

### ISSUE THREAD

**Issue by yurivict** [hishamhm/htop#754] opened 2018-03-05 17:56 UTC
Could you please make this target https://github.com/hishamhm/htop/blob/master/Makefile.am#L119 dev-only so that there is no chance that the python script can be accidentally run during the package build? You can run it manually when you need to regenerate them. Python executable can have different paths on different systems. It needs to be patched. And it only doesn't run because of the favorable timestamp combination, which is somewhat arbitrary.

For example, the target can be named ```dev-regenerate-headers```.

**Comment by Explorer09** [comment] 2018-03-07 01:05
The headers will need to be updated to reflect the source code changes, and yes, this means that you need Python to build htop if you have modified the source.

And what was your problem of running Python to regenerate headers then?

By the way, I like the `regenerate-headers` target idea and did plan to make it in the makefile, when I have the free time. (I'll probably name the target `htop-headers` instead but would work the same.)

**Comment by yurivict** [comment] 2018-03-07 02:30
> The headers will need to be updated to reflect the source code changes, and yes, this means that you need Python to build htop if you have modified the source.

You already supply the rebuilt headers.

> And what was your problem of running Python to regenerate headers then?

Python needs to be installed by the port. Since the headers are actually ready, it doesn't get triggered. But if some timestamp will be wrong the python script will run. A lot of unnecessary complexity stems from this.

**Comment by Explorer09** [comment] 2018-03-07 03:38
@yurivict Seeing the timestamps wrong means the headers need to be updated, and it is what `make` is designed for. There's nothing wrong with it. The problem you will face is instead that older headers get shipped in the distribution tarballs, and so we need `dist-hook` to force update them.

**Comment by yurivict** [comment] 2018-03-07 03:46
You should always ship with updated headers. This is a small matter, but since this python script can accidentally run we need to always keep python installed, which complicates the port.This complication is what causes questions. People look into why python is needed. Then they find that it isn't really needed because they are already up-to-date. But what if next time they will not be up-to-date, then we need to keep python. This complicates things.

**Comment by Explorer09** [comment] 2018-03-07 03:58
@yurivict I don't believe what you called the "accidentally running" is caused by the header rule (`.c.h:`) you mentioned. Rather, it's the inclusion of headers in `BUILT_SOURCES` Automake variable that may cause it.
htop's makefile should have tracked the dependencies explicitly instead.

**Comment by hishamhm** [comment] 2018-03-16 14:27
> The problem you will face is instead that older headers get shipped in the distribution tarballs, and so we need dist-hook to force update them.

If I'm following this correctly (I don't recall older headers being shipped in the official tarball, but I wouldn't rule it out), then making sure `make dist` prevents this sounds like the right way to go, for me.

**Comment by yurivict** [comment] 2018-03-16 17:44
Yes, just move auto-generation into ```make dist```. This sounds good.

**Comment by Explorer09** [comment] 2018-03-17 01:38
@hishamhm @yurivict 
I have to correct one fact here: Currently htop `make dist` will package with updated headers (never out of date) thanks to the inclusion of headers in $(myhtopplatheaders) and $(htop_SOURCES). (Despite that they may be conditionally built in `make all`.) So technically I don't need extra `dist-hook` to do what Automake has done for us.

Anyway, I still like a pair of makefile targets to quickly clean and rebuild htop headers.

**Comment by Explorer09** [comment] 2018-03-17 01:59
Here you are: #763 
And for @yurivict: If you really like to skip headers generation, you _can_ trick htop's build system by `make -t htop-headers`. Of course I trust what you are doing.

**Comment by yurivict** [comment] 2018-03-17 02:19
> If you really like to skip headers generation, you can trick htop's build system by make -t htop-headers.

Adding ```-t``` doesn't rebuild anything, only touches .o files too. And there is no such target ```htop-headers```.

**Comment by Explorer09** [comment] 2018-03-17 03:37
@yurivict 
Sorry I meant "after the pull request #763 change".
The new htop-headers target is what I propose in the pull request.

**Comment by hishamhm** [comment] 2018-03-25 18:40
I merged in @Explorer09's PR with the `htop-headers` utility targets.

Since `make dist` does update all headers, I'm closing this one. Distribution installations should be made from the release tarballs, that include all header files.

**Closed by hishamhm** 2018-03-25 18:40 UTC
