### ISSUE TITLE
htop crashes on settings setup [Arch Linux]

### ISSUE THREAD

**Issue by GnomoP** [hishamhm/htop#723] opened 2018-01-31 00:23 UTC
I've been using htop for quite awhile without running into any issues. However, after opening two htop processes under the same user to change the settings while keeping the process list visible, I can't change them anymore, nor can I solve the issue by reinstalling the package through pacman.

htop.objdump file at https://goo.gl/soozBC

```htop(CRT_handleSIGSEGV+0x36)[0x55c95bdc8986]
/usr/lib/libc.so.6(+0x348e0)[0x7f854e63f8e0]
htop(String_freeArray+0x9)[0x55c95bdc05c9]
htop(Header_writeBackToSettings+0x4f)[0x55c95bdb8def]
htop(+0x19a7b)[0x55c95bdc3a7b]
htop(+0xde5a)[0x55c95bdb7e5a]
htop(ScreenManager_run+0x279)[0x55c95bdbeb69]
htop(main+0x414)[0x55c95bdb5604]
/usr/lib/libc.so.6(__libc_start_main+0xea)[0x7f854e62bf4a]
htop(_start+0x2a)[0x55c95bdb583a]```

**Comment by hishamhm** [comment] 2018-02-04 18:56
I can't reproduce here locally. What htop version are you running?

**Comment by hishamhm** [comment] 2018-02-04 18:56
(If your settings got corrupted, you can delete ~/.config/htop/htoprc to go back to the defaults, but consider sending it to me by email at h@hisham.hm first)

**Comment by hishamhm** [comment] 2018-02-05 10:23
Ok, I confirmed this was a bug in htop 2.0.1. Closing this for now, feel free to reopen if it appears in the latest release!

**Closed by hishamhm** 2018-02-05 10:23 UTC
