### ISSUE TITLE
Core Dump while filtering

### ISSUE THREAD

**Issue by Gamah** [hishamhm/htop#189] opened 2015-05-01 00:17 UTC
Reproduction steps:
1.) Run htop
2.) Press F4
3.) Search for any string
4.) Press End, Home, End

#Begin backtrace
htop[0x4096f7]
/lib/x86_64-linux-gnu/libc.so.6(+0x352f0)[0x7f901ee232f0]
htop(Panel_draw+0x1f2)[0x40e2f2]
htop(main+0x6a1)[0x406111]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f901ee0ea40]
htop[0x407aeb]
#End backtrace

objdump file:
https://gist.githubusercontent.com/Gamah/779cec615281c88a8a59/raw/htop.objdump

**Comment by gajownik** [comment] 2015-05-01 00:37
What version of htop are you using?

**Comment by Gamah** [comment] 2015-05-01 00:45
1.0.2

**Comment by gajownik** [comment] 2015-05-01 01:08
Might be a duplicate of #76 Could you please try a version from git?

**Comment by hishamhm** [comment] 2015-05-13 18:07
It is a duplicate — closing! Thanks @Gamah for the report and @gajownik for the feedback!

**Closed by hishamhm** 2015-05-13 18:07 UTC
