### ISSUE TITLE
Problem with rendering 80 CPUs

### ISSUE THREAD

**Issue by Technologov** [hishamhm/htop#821] opened 2018-07-30 22:33 UTC
When running on a 80-CPU Xeon server, the htop CPU % rendering is severely garbled (garbage).

![htop-80-cpus-2018-07-31](https://user-images.githubusercontent.com/1480628/43427286-a1a7584c-9461-11e8-81b1-e33ca606ee9d.png)

This problem doesn't exist with smaller 24-CPU and 16-CPU servers.
Running Ubuntu 18.04 (with distro-supplied htop 2.1.0)

**Comment by michael-o** [comment] 2018-08-05 21:00
You should try from master first...

**Comment by spauka** [comment] 2018-08-22 12:46
This is potentially caused by a recent change in `terminfo`. Similar issue here: https://unix.stackexchange.com/questions/394787/linux-terminal-skipping-some-repeating-whitespace-characters

**Comment by hishamhm** [comment] 2018-08-24 21:51
@spauka Thank you for the pointer! I'm proceeding to close this since it's not an htop-specific issue.

**Closed by hishamhm** 2018-08-24 21:51 UTC
