### ISSUE TITLE
Default color scheme shows black background under some elements on xterm

### ISSUE THREAD

**Issue by magiblot** [hishamhm/htop#747] opened 2018-02-24 19:00 UTC
Hi there.

I'm on ArchLinux x86-64 and I have the 2.1.0-2 htop package installed.

For the last, I think, one or two updates (I'm sorry I can't tell you exactly), when running htop on xterm, I have been seeing some elements being rendered with a black background instead of keeping the terminal's color.:
![screenshot_20180224_193637](https://user-images.githubusercontent.com/20713561/36633745-fa2876d2-199a-11e8-9321-2f569ac87f5a.png)

The only color schemes affected by this are Default and Light Terminal. I could not reproduce the issue in konsole.

![screenshot_20180224_195045](https://user-images.githubusercontent.com/20713561/36633873-b15c8c2a-199c-11e8-8b53-19cb1b824c01.png)

I used not to have this issue, so I guess this may be some kind of regression.

Thanks a lot.

**Comment by Explorer09** [comment] 2018-02-26 12:44
Can you build and run htop from the latest git master? Because there have been a commit ac2dff2881a7ab203750e8edf7a46b69ae492ed0 that might have fixed your problem. Or are you saying that it is this commit that caused the regression?

**Comment by hishamhm** [comment] 2018-02-26 13:17
The screenshot show it's 2.1.0, so it's definitely the issue in the release version. As @Explorer09 said, the fix is in `master`, upcoming in 2.1.1. Thank you for reporting!

**Closed by hishamhm** 2018-02-26 13:17 UTC
