### ISSUE TITLE
Per Core Utilization

### ISSUE THREAD

**Issue by PatilChetan** [hishamhm/htop#769] opened 2018-03-27 19:10 UTC
Hi All,

I am trying to understand how htop calculates per core utilization irrespective of the Intel system it's running on?

Any generic Intel performance counters that it uses?

Thanks.

**Comment by hishamhm** [comment] 2018-04-06 14:06
No, it uses `/proc/stat`. You can check out the source for details! :)

Closing this one since it is not a bug report. Cheers!

**Closed by hishamhm** 2018-04-06 14:06 UTC
