### ISSUE TITLE
Htop statistical memory usage errors

### ISSUE THREAD

**Issue by Hello-Linux** [hishamhm/htop#570] opened 2016-10-21 03:25 UTC
Linux htop statistics of physical memory, in which the cache and used  is not correct and my Linux'system is Centos 6.5

**Comment by Explorer09** [comment] 2016-10-21 03:28
How do you define "incorrect"? Can you show us a data example of what's wrong, with the comparison of the original /proc/meminfo data reported from the kernel?

By the way, tell us the htop version you are using (this is required for your issue reporting).

**Comment by Hello-Linux** [comment] 2016-10-21 03:41
Then I use the command free -mh and the  results of is " 
                 total       used       free     shared    buffers     cached
Mem:          7.7G       5.3G       2.5G       340K       570M       3.5G
-/+ buffers/cache:       1.2G       6.5G
Swap:         4.0G         0B       4.0G
  but the Htop  show " used memory is 260M  the cached is 4.46G",our /proc/meminfo is "cat /proc/meminfo
MemTotal:        8111200 kB
MemFree:         2505880 kB
Buffers:          587080 kB
Cached:          3667976 kB
SwapCached:            0 kB
"
The Hop's version is 2.0.2,So I think is a Hop's bug? or error?

**Comment by Explorer09** [comment] 2016-10-21 04:20
The problem is, I cannot reproduce the error you have. The values are correct in my machine (Ubuntu 14.04, htop 2.0.2 built from checked-out git source repo). So you need to provide more information.

Maybe your htop binary packed in a tarball would help.

**Comment by Hello-Linux** [comment] 2016-10-21 05:29
And thank your for your suggest,this problem  is  appear  in one of  my machine but not all,May be the installation process where I went wrong

**Comment by hishamhm** [comment] 2016-10-25 18:42
I cannot not reproduce this, either. Can you post a screenshot with four terminal windows, running:

* `htop`
* `top`
* `watch free -h`
* `watch cat /proc/meminfo`

Make sure all terminals are logged to the same machine!

**Comment by Hello-Linux** [comment] 2016-10-28 03:05
@hishamhm  The following is my screenshots on the same machine：
![free -h](https://cloud.githubusercontent.com/assets/17851645/19793182/66a8ff7c-9cfe-11e6-86dd-355cb887bfc4.png)
![htop](https://cloud.githubusercontent.com/assets/17851645/19793180/661eda54-9cfe-11e6-919c-2657486cd9ce.png)
![meminfo](https://cloud.githubusercontent.com/assets/17851645/19793178/65351fb8-9cfe-11e6-9829-7c3a442c4471.png)
![top](https://cloud.githubusercontent.com/assets/17851645/19793181/661f4818-9cfe-11e6-8be0-57ec6ba0cf6f.png)

**Comment by Hello-Linux** [comment] 2016-10-28 03:23
@hishamhm Memory statistics through the use of the above screenshot shows htop is wrong, but this is not all the machines to. Another problem is that I installed the first 6.0 then install ncurses htop6.0, can't scroll and htop shows blank Below is a screenshot:
![qq 20161028112202](https://cloud.githubusercontent.com/assets/17851645/19793796/fb40abb0-9d00-11e6-9635-142d11c2d729.png)

**Comment by Explorer09** [comment] 2016-10-28 04:41
@Hello-Linux Please don't put two issues in one report. Move your second one into a new report instead.
And for your htop screenshot, could you also show us the text view of the memory meter, side by side, like this?
![selection_269](https://cloud.githubusercontent.com/assets/2487263/19795154/d1ebcbcc-9d0b-11e6-818b-276095240caf.png)

**Comment by Explorer09** [comment] 2016-10-28 04:47
And when you are at it, could you mail us the binary you built, so that we can analyze it and see what could be wrong in your build?

**Comment by hishamhm** [comment] 2016-10-28 20:36
@Hello-Linux I asked for one screenshot with four terminals because I wanted to see the results of the commands _at the same time_ :) But your screenshots were a good enough approximation, they were enough to solve the mystery. (Don't worry, there is no need to send me the binary.)

The /proc/meminfo screenshot shows that there are 2.37GB of memory marked as SReclaimable: this is a kernel cache. htop identifies that as a cache in the meter, because that is not really "occupied" memory: this cache can be reclaimed as free space if your programs need more RAM). Your version of free is failing to display that. Check here for details: https://github.com/hishamhm/htop/pull/263

**Closed by hishamhm** 2016-10-28 20:36 UTC

**Comment by Explorer09** [comment] 2016-10-29 01:38
@hishamhm I believe this behavior should be documented. As many users are not yet aware of this and assumes htop calculates the data wrong.

And by the way, there could be a "detailed memory" feature, just like how we have "detailed CPU time".
