### ISSUE TITLE
htop 2.0.1 (Ubuntu 16.04)  - crash after set cpu affinity attempt

### ISSUE THREAD

**Issue by smartass111** [hishamhm/htop#522] opened 2016-06-28 13:23 UTC
Hi
I'm running htop under 16.04 Ubuntu on thinkpad x220 laptop
when I try to select some process, type "a" and unselect some cpu's - I'm getting crash after "enter" hit (in 100% cases)

here is the output
```
htop 2.0.1 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop(CRT_handleSIGSEGV+0x33)[0x55b320689ef3]
/lib/x86_64-linux-gnu/libc.so.6(+0x354a0)[0x7f52acf254a0]
htop(Affinity_set+0x2b)[0x55b320683bbb]
htop(MainPanel_foreachProcess+0xa8)[0x55b320679e98]
htop(+0x195a5)[0x55b3206855a5]
htop(+0xdd0f)[0x55b320679d0f]
htop(ScreenManager_run+0x1dd)[0x55b32068045d]
htop(main+0x4f4)[0x55b320677624]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f52acf10830]
htop(_start+0x29)[0x55b320677799]
```

[htop.objdump.zip](https://github.com/hishamhm/htop/files/337108/htop.objdump.zip)

and here is my system info
```
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```

**Comment by hishamhm** [comment] 2016-06-28 18:25
Thank you for the report, the bug is fixed in current Git! (duplicate of #493)

**Closed by hishamhm** 2016-06-28 18:25 UTC
