### ISSUE TITLE
"Page Down" and "Page Up" work a bit different

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#532] opened 2016-08-04 16:31 UTC
I'm using htop 2.0.2 and for example if I'm within a small view of the process list, selecting the first process of it and then pressing "Page Down" the last process of the current view gets selected and if I'm then pressing "Page Up" the first process of the current view gets selected but additionally the view gets moved 1 up. I think either pressing "Page Down" should cause the same shift of the view or on pressing "Page Up" the shift should not appear there anymore to make the behavior of these keys consistent.

**Comment by Explorer09** [comment] 2016-08-06 11:35
Can you show us a concrete example? I mean, show us a "steps to reproduce", "actual behavior", and "expected behavior" just as if this was a bug, and you were writing a bug report in a format that's required for many other projects.

Even it's about a behavior difference, writing this issue like a bug report can help us be more clear what you're talking about.

**Comment by Sworddragon** [comment] 2016-08-06 19:53
Steps to reproduce:

1. Start htop and make sure you have enough processes listed (for example by shrinking the window) so that you can shift the process view at least 2 times by pressing "Page Down".
2. Go back to the first process.
3. Press "Page Down" 2 times and then go to the first process of the current process view.
4. Press "Page Down" and then "Page Up".

Actual result:

At step 4 on pressing "Page Down" the last process in the current process view is selected and on pressing "Page Up" the first process of the current process view is selected and then the process view is moved 1 up so that the selected process is the last process in the new process view.

Expected result:

At step 4 either pressing "Page Down" should select the last process of the current process view (as it is currently done) and additionally moving the process view 1 down so that the selected process is the first process in the new process view or pressing "Page Up" should only select the first process of the current process view.

**Comment by Explorer09** [comment] 2016-08-06 23:13
Reproduced on my computer. Thanks. This behavior inconsistency is caused by commit 759caf0f8fa593430adea676fc64612b5197dca8 "Make PgDown behavior more usual."

**Comment by Explorer09** [comment] 2016-08-07 12:50
@Sworddragon Would you checkout the code in my branch in pull request #534 and test it out by yourself? It's good to let all of us know whether my fix works in your expectations.

**Comment by Sworddragon** [comment] 2016-08-07 23:03
Testing is commonly done after a new release. As long as you could reproduce this issue and confirm it being fixed with your patch all should be fine. If I should find any (additional) bugs/ideas after testing in the future I will create tickets for them.

**Comment by hishamhm** [comment] 2016-08-09 16:07
I just checked @Explorer09's patch and its behavior against other apps; it seems indeed better now. Merged, thank you both!

**Closed by hishamhm** 2016-08-09 16:07 UTC
