### ISSUE TITLE
100% load for singe CPU core

### ISSUE THREAD

**Issue by poiuty** [hishamhm/htop#202] opened 2015-06-03 07:53 UTC
Hello, my favorite toolkit author! I have found very strange issue with htop (1.0.3). Sometimes it show 100% load for singe CPU core. But actually I checked CPU consumption with mpstat and top  in same time and haven't saw any 100% consumption for any CPU. Could you check this?

Also htop 1.0.1 not show this => https://poiuty.com/img/45bf0370d934efecd40a41156509.png
Debian 8, 3.16.0-4-amd64

**Comment by kerframil** [comment] 2015-07-22 13:12
I have noticed the same. I just want to add that the problem occurs irrespective of the value of the --delay parameter. Further, in my case, htop-1.0.3 usually reports 100% saturation of all cores for at least the first delta after having been started. If it matters, most of my systems have two hexa-core processors, yielding 24 logical cores.

**Comment by kerframil** [comment] 2015-07-24 01:28
Bisection reveals the following commit as being responsible.

af285d1d3bb182c3f09c70110f4305cb19437245 `Fixes in accounting of guest time when using virtualization`

The box that I am testing is a Linux KVM host - not a guest. The option to add guest time to the CPU meter is disabled.

`[ ] Add guest time in CPU meter percentage`

If I understand this correctly, this commit is either intended to improve the accuracy of CPU accounting in a guest or pertains to the above mentioned option. Either way, it seems to be responsible for inaccurate readings on the host.

**Comment by hishamhm** [comment] 2015-08-19 18:09
@poiuty, thanks for the bug report!
@kerframil, thanks for the bisect analysis!

What kernel version are you guys running?

**Comment by poiuty** [comment] 2015-08-19 18:10
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

**Comment by hishamhm** [comment] 2015-08-19 19:46
I had no success yet in tracking what could cause problems with af285d1... I just sent an email to Patrick Marlier, the patch author, hopefully he can help!

**Comment by maskur** [comment] 2015-08-20 14:49
Patrick Marlier and I looked into this bug report, but I am not sure we fully understood the problem. Could you please provide a scenario to reproduce the wrong behavior (what workloads are running in the VM, what is the configuration of the VM,...)? Thanks!

**Comment by poiuty** [comment] 2015-08-20 15:00
all pkg from from apt-get repo debian 8
install htop, kvm-qemu, virsh, libvirt
create debian vm and install LAMP server with low load (0~20%)

open htop (node) => sometimes we see 100%
open htop (vm) => no 100%
open top (node) => no 100%

Also, when we see 100% => no process => who use this cpu
https://poiuty.com/img/ba882296d303b83e88ceb9ee8643.png

**Comment by maskur** [comment] 2015-08-20 16:20
Thank you. We were able to reproduce the problem. There seems to be a overflow problem, when updating the cpuData->userPeriod (ProcessList.c, line 969). We are not sure yet where this is coming from, but a temporary fix could be

cpuData->userPeriod = usertime - cpuData->userTime;
----->
cpuData->userPeriod = usertime+1 - cpuData->userTime;

since usertime is only slightly smaller than cpuData->userTime.

**Comment by milosivanovic** [comment] 2015-08-24 16:07
I'd just like to chip in and say that I too noticed this when htop 1.0.3 was released but didn't have the time to look into it; instead, I just stayed on htop 1.0.2.

The proposed workaround does work as described, but it will be adding usertime that was never there in the first place, resulting in false readings (a very slight increase of what the actual processor usage will be at any given moment). This is most noticeable with an idle system.

I'm unsure if @kerframil's report is related to this bug, which remains even with the workaround implemented (hence the thought that it probably isn't related). @kerframil is talking about all cores displaying 100% usage when htop is first invoked, until the next delta cycles in, whereas this bug report is talking about displaying 100% usage for a single core *randomly* while htop is running.

I have confirmed both bugs as of 8f07868f, but a new issue should be opened for what @kerframil is reporting unless I am somehow mistaken.

**Comment by kerframil** [comment] 2015-08-24 16:56
I commented because I was experiencing the exact same issue that @poiuty is, for which I carried out the bisection. The issue of how htop behaves for the first delta after being started is something that seemed relevant.

I haven't tested the aforementioned workaround yet. I'm not certain that things have moved along to the extent that the latter issue can be definitively classified as another bug i.e. with distinct underlying causes. If there is evidence to the contrary then it should indeed be filed as a new bug.

Also, regarding the kernel version, the affected machine is running 3.6.8 (with very few patches).

**Comment by kerframil** [comment] 2015-08-24 17:23
@maskur In terms of workload, the affected machine is a KVM host, running 32 guest machines in qemu. The majority of these guest machines run Ubuntu 12.04 LTS and the workload is highly varied among them. Some serve as a test bed for in-house Java applications which, in turn, require others that provide services including MySQL, HBase, OpenTSDB and NFS. However, none of these guest machines are used for production purposes and the cumulative load is, therefore, low by our standards. There will be the odd spike here and there but this does not account for the behaviour described by this bug.

The host is a Dell PowerEdge R410 with 2 x Xeon X5650 processors and 96G RAM. It has KSM (Kernel Samepage Merging) enabled. The median configuration for a guest is 2 CPUs and 2G RAM. All of the operating systems running in the guests are using paravirt drivers - including the solitary Windows machine among them.

Here is a representation of the load average of the host, which has 24 logical CPU cores, over a 24-hour period. The samples were taken at 5 minute intervals.

![kvm1-load-day](https://cloud.githubusercontent.com/assets/889778/9446757/331da930-4a8b-11e5-92ba-70c5ac940d6b.png)

If you require any further information, feel free to ask.

**Comment by patrickmarlier** [comment] 2015-08-24 17:46
I checked a bit the kernel source and I don't really explain why the user time stays the same while the guest time increases. Indeed, in the kernel, it adds the guest time to user time so it could be a rounding effect due to cputime64_to_clock_t?
Hisham any advice on how we could fix this? One possibility is to remove the assert for usertime and nicetime and instead if overflow to put it to 0.

**Comment by patrickmarlier** [comment] 2015-08-28 17:38
Here I see 2 issues (kernel 4.1.6):

kernel/sched/cputime.c:account_guest_time()
>   cpustat[CPUTIME_USER] += (__force u64) cputime;
>   cpustat[CPUTIME_GUEST] += (__force u64) cputime;

There is no synchronization in the cpustat data-structure. One example is if one thread is reading the 2 values while one thread has only updated the fisrt value yet. This is unlikely but I think this can happen.


fs/proc/stat.c:show_stat()
> seq_put_decimal_ull(p, ' ', cputime64_to_clock_t(user));

cputime64_to_clock_t() convert types and this rounding is probably the problem we are seeing.
Example:
>                    cputime64 -> clock_t
>        user:     41892000000 -> 4189
>        guest:    37788000000 -> 3778

The difference with the output of /proc/stat, we get 411. However if you do the same using, cputime64 in the kernel, you will get 4104000000 that is closer to 410 than 411. So finally if you take values at 2 different time, you cannot be sure about the rounding and led to this possible difference of 1.

Opinions on how to fix? I propose to remove the assert and check for overflows but I am open to all possible fix.

**Comment by hishamhm** [comment] 2015-08-28 19:12
> Hisham any advice on how we could fix this? One possibility is to remove the assert for usertime and nicetime and instead if overflow to put it to 0.

If it all comes down to a rounding glitch that leaks from the kernel, then I think this is the most sensible approach. Thank you @maskur and @patrickmarlier for the amazing hunter work!

(@kerframil @milosivanovic, yes, I believe the incorrect values in the first iteration is due to a different problem, so this should probably be a separate bug entry.)

**Comment by patrickmarlier** [comment] 2015-09-14 21:10
If somebody can give it a try, I am proposing a fix. See branch issue202 in my htop fork.
Thanks.

**Comment by poiuty** [comment] 2015-10-25 08:26
@patrickmarlier, no it`s not help.

<img src="https://poiuty.com/img/76/f59ea3ef43ddd8db0a37ebfad95d8d76.png">

<img src="https://poiuty.com/img/b1/258c6955d603f63213461532d869cbb1.png">

**Comment by poiuty** [comment] 2015-10-25 08:30
Sorry, my bad (test main branch).
re-test => issue202 work nice => no 100%

**Comment by hishamhm** [comment] 2015-10-26 21:55
Merged! Thanks @patrickmarlier!

**Comment by hishamhm** [comment] 2015-10-26 21:55
Thank you @poiuty for testing!

**Closed** 2015-10-26 21:55 UTC
